/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding/team'
import { Route as OnboardingReadyRouteImport } from './routes/onboarding/ready'
import { Route as OnboardingAppsRouteImport } from './routes/onboarding/apps'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as AuthenticatedSuccessRouteImport } from './routes/_authenticated/success'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPipelinesRouteImport } from './routes/_authenticated/pipelines'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAutonomyRouteImport } from './routes/_authenticated/autonomy'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsWorkspaceRouteImport } from './routes/_authenticated/settings/workspace'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsDeveloperRouteImport } from './routes/_authenticated/settings/developer'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAppsRouteImport } from './routes/_authenticated/settings/apps'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReadyRoute = OnboardingReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAppsRoute = OnboardingAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => OnboardingRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuccessRoute = AuthenticatedSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelinesRoute = AuthenticatedPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutonomyRoute = AuthenticatedAutonomyRouteImport.update({
  id: '/autonomy',
  path: '/autonomy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsWorkspaceRoute =
  AuthenticatedSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDeveloperRoute =
  AuthenticatedSettingsDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppsRoute =
  AuthenticatedSettingsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/autonomy': typeof AuthenticatedAutonomyRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/pipelines': typeof AuthenticatedPipelinesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/signals': typeof AuthenticatedSignalsRoute
  '/success': typeof AuthenticatedSuccessRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/apps': typeof AuthenticatedSettingsAppsRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/autonomy': typeof AuthenticatedAutonomyRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/pipelines': typeof AuthenticatedPipelinesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/success': typeof AuthenticatedSuccessRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/apps': typeof AuthenticatedSettingsAppsRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/autonomy': typeof AuthenticatedAutonomyRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/pipelines': typeof AuthenticatedPipelinesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/success': typeof AuthenticatedSuccessRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/onboarding/apps': typeof OnboardingAppsRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/apps': typeof AuthenticatedSettingsAppsRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/developer': typeof AuthenticatedSettingsDeveloperRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/apps'
    | '/autonomy'
    | '/chat'
    | '/overview'
    | '/pipelines'
    | '/reports'
    | '/settings'
    | '/signals'
    | '/success'
    | '/accept-invitation/$id'
    | '/onboarding/apps'
    | '/onboarding/ready'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/apps'
    | '/settings/billing'
    | '/settings/developer'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/apps'
    | '/autonomy'
    | '/chat'
    | '/overview'
    | '/pipelines'
    | '/reports'
    | '/signals'
    | '/success'
    | '/accept-invitation/$id'
    | '/onboarding/apps'
    | '/onboarding/ready'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/apps'
    | '/settings/billing'
    | '/settings/developer'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/workspace'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/activity'
    | '/_authenticated/alerts'
    | '/_authenticated/apps'
    | '/_authenticated/autonomy'
    | '/_authenticated/chat'
    | '/_authenticated/overview'
    | '/_authenticated/pipelines'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/signals'
    | '/_authenticated/success'
    | '/accept-invitation/$id'
    | '/onboarding/apps'
    | '/onboarding/ready'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/_authenticated/chat/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/apps'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/developer'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/workspace'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/ready': {
      id: '/onboarding/ready'
      path: '/ready'
      fullPath: '/onboarding/ready'
      preLoaderRoute: typeof OnboardingReadyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/apps': {
      id: '/onboarding/apps'
      path: '/apps'
      fullPath: '/onboarding/apps'
      preLoaderRoute: typeof OnboardingAppsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/success': {
      id: '/_authenticated/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthenticatedSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipelines': {
      id: '/_authenticated/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof AuthenticatedPipelinesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autonomy': {
      id: '/_authenticated/autonomy'
      path: '/autonomy'
      fullPath: '/autonomy'
      preLoaderRoute: typeof AuthenticatedAutonomyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/workspace': {
      id: '/_authenticated/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/developer': {
      id: '/_authenticated/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AuthenticatedSettingsDeveloperRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/apps': {
      id: '/_authenticated/settings/apps'
      path: '/apps'
      fullPath: '/settings/apps'
      preLoaderRoute: typeof AuthenticatedSettingsAppsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppsRoute: typeof AuthenticatedSettingsAppsRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsDeveloperRoute: typeof AuthenticatedSettingsDeveloperRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsWorkspaceRoute: typeof AuthenticatedSettingsWorkspaceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppsRoute: AuthenticatedSettingsAppsRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsDeveloperRoute: AuthenticatedSettingsDeveloperRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsWorkspaceRoute: AuthenticatedSettingsWorkspaceRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedAutonomyRoute: typeof AuthenticatedAutonomyRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPipelinesRoute: typeof AuthenticatedPipelinesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedSuccessRoute: typeof AuthenticatedSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedAutonomyRoute: AuthenticatedAutonomyRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPipelinesRoute: AuthenticatedPipelinesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedSuccessRoute: AuthenticatedSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingAppsRoute: typeof OnboardingAppsRoute
  OnboardingReadyRoute: typeof OnboardingReadyRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAppsRoute: OnboardingAppsRoute,
  OnboardingReadyRoute: OnboardingReadyRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
