import { createEnv } from "@t3-oss/env-core"
import { z } from "zod"

export const env = createEnv({
  server: {
    PORT: z.string().min(1),
    CORS_ORIGIN: z.string(),
    CRON_SECRET: z.string().default(""),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().default(""),
    OPENROUTER_AI_API_KEY: z.string().min(1),
    POLAR_ACCESS_TOKEN: z.string().min(1),
    POLAR_SERVER: z.enum(["sandbox", "production"]).default("sandbox"),
    POLAR_PRODUCT_ID: z.string().min(1),
    POLAR_STARTER_PRODUCT_ID: z.string().min(1),
    POLAR_GROWTH_PRODUCT_ID: z.string().default(""),
    POLAR_SUCCESS_URL: z.url(),
    UPSTASH_REDIS_REST_URL: z.url(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(32),
    BETTER_AUTH_URL: z.url(),
    PUBLIC_API_URL: z.url().optional(),
    SLACK_CLIENT_ID: z.string().default(""),
    SLACK_CLIENT_SECRET: z.string().default(""),
    SLACK_SIGNING_SECRET: z.string().default(""),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().default(""),
    GITHUB_CLIENT_SECRET: z.string().default(""),
    POLAR_APP_CLIENT_ID: z.string().default(""),
    POLAR_APP_CLIENT_SECRET: z.string().default(""),
    POLAR_WEBHOOK_SECRET: z.string().default(""),
    BLOB_READ_WRITE_TOKEN: z.string().min(1),
    BLOB_STORE_ID: z.string().min(1).optional(),
    APP_NAME: z.string().min(1),
  },
  runtimeEnv: process.env,
  emptyStringAsUndefined: true,
})
